<?php

/**
 * Template part for displaying page content in page.php
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/
 *
 * @package Find_Dinppo
 */
// global $wp_query;
// $max_pages = $wp_query->max_num_pages;
// echo $max_pages;
?>
<style type="text/css">
@keyframes ldio-ebuuj6igisj {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-ebuuj6igisj div {
	/* position: absolute; */
    animation: ldio-ebuuj6igisj 1s linear infinite;
    width: 60px;
    height: 60px;
    top: 50%;
    left: 50%;
    border-radius: 50%;
    box-shadow: 0 4px 0 0 #e15b64;
    /* transform-origin: 50% 50%; */
/*     margin-top: 20px; */
/*   position: absolute;
  animation: ldio-ebuuj6igisj 1s linear infinite;
  width: 64px;
  height: 64px;
  top: 50%;
  left: 50%;
  border-radius: 50%;
  box-shadow: 0 4px 0 0 #e15b64;
  transform-origin: -50% -50%; */
}
.loadingio-spinner-eclipse-vlgr8szkp9 {
	width: 200px;
	height: 200px;
	display: inline-block;
/* 	overflow: hidden; */
	background: transparent;
}
.ldio-ebuuj6igisj {
	width: 100%;
	height: 100%;
	position: relative;
	transform: translateZ(0) scale(1);
	backface-visibility: hidden;
  	transform-origin: 0 0; /* see note above */
	display:flex;
	justify-content: center;
	align-items:center;
}
.ldio-ebuuj6igisj div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?> style="max-width: 600px; margin: 0 auto;">

	<!-- Zip-code Search Section -->
	<div class="row mb-4 ppo-b1-red ppo-box-shadow ppo-br-16 bg-white overflow-hidden">
		<form action="" method="get" class="p-0 m-0">
			<div class="d-flex w-100">
				<button type="submit" class="ppo-b-0 ppo-br-16 bg-white">
					<img src="<?php echo ppo_get_dir('/assets/images/zipcode/search-icon.png') ?>" style="width:20px;" />
				</button>
				<input type="search" name="" id="ppoZipSearch" placeholder="Indtast postnummer" class="px-3 ppo-b-0 w-100 ppo-br-16 ppo-search-input border-0">
			</div>
		</form>
	</div>


	<!-- Filter Section -->
	<div class="row mb-4 justify-content-center">
		<div class="w-75 p-0  ppo-br-16 ppo-b2-secondary ppo-bg-card">

			<div class="ppo-box-shadow ppo-br-16 py-1 px-5 text-center ppo-bg-secondary">
				<div class="d-flex py-1 justify-content-center align-items-center" style="height:30px;">
					<span class="text-light fs-5 fw-bold">Filtrer</span>
					&nbsp;&nbsp;&nbsp;
					<span class="position-relative vertical-center text-center ppo-filter-icon" onclick="ppoToggleFilterContent();">
						<span></span>
					</span>
				</div>
			</div>

			<!-- Years Section -->
			<div class="p-3" id="ppoFilterContent" style="display:none;">

				<p class="text-light text-center fw-bold fs-3 mb-0">Ledige pladser:</p>

				<!-- Years -->
				<div class="w-100 mb-3">

					<p class="text-left text-light fw-regular fs-3 mb-0">År:</p>

					<!-- Years -->
					<div class="row py-2">
						<div class="col-2"></div>
						<?php
						$current_year = date("Y");
						$year_increased = 0;

						while ($year_increased < 3) :
							$year = intval($current_year) + $year_increased;
						?>
							<div class="col-3">
								<button class="btn text-light fw-bold fs-5  ppo-profile-cal-button<?php echo ($year_increased == 0 ? ' active' : ''); ?>" data-targeted-year="<?php echo trim($year); ?>"><?php echo trim($year); ?></button>
							</div>
						<?php
							$year_increased++;
						endwhile;
						?>
						<div class="col-1"></div>
					</div>

				</div>

				<!-- Months Section -->
				<div class="w-100 mb-3">

					<p class="text-left text-light fw-regular fs-3 mb-0">Måned:</p>

					<?php
					$months = array(
						'jan' => "Jan",
						'feb' => "Feb",
						'mar' => "Mar",
						'apr' => "Apr",
						'maj' => "Maj",
						'jun' => "Jun",
						'jul' => "Jul",
						'aug' => "Aug",
						'sep' => "Sep",
						'okt' => "Okt",
						'nov' => "Nov",
						'dec' => "Dec",
					);
					?>
					<!-- Months -->
					<div class="ppo-cal-month-content py-3">
						<?php
						foreach ($months as $key_month_name => $month) :
						?>
							<button class="btn text-white fw-bold fs-6  ppo-profile-cal-button" data-targeted-month="<?php echo esc_html($key_month_name); ?>"><?php echo $month; ?></button> <!-- /.disabled - if needed -->
						<?php
						endforeach;
						?>
					</div>

				</div>

				<!-- Subscription Plans Section -->
				<div class="w-100">

					<p class="text-left text-light fw-regular fs-3 mb-0">Søg efter foreksllige PPO'ser: <img src="<?php echo ppo_get_dir('/assets/images/zipcode/letter-i.png') ?>" style="width: 30px;" /></p>

					<?php
					$plans = ppo_get_subscription_plan_list();
					?>
					<!-- Stars -->
					<div class="ppo-stars-content pb-3 pt-2">
						<?php
						foreach ($plans as $plan_name => $plan) :
						?>
							<button class="btn px-1 text-center text-white fw-bold fs-6" data-targeted-plan="<?php echo esc_html($plan_name); ?>">
								<p class="text-light mb-2" style="pointer-events: none;"><?php echo esc_html($plan['plan']); ?></p>
								<img src="<?php echo esc_html($plan['star_icon']); ?>" style="width:60px;pointer-events: none;" class="d-block ppo-br-12 p-1 ppo-bg-secondary" />
							</button> <!-- /.disabled - if needed -->
						<?php
						endforeach;
						?>
					</div>

				</div>

				<div class="text-center">
					<button class="btn py-1 mb-2 w-50 ppo-br-16 align-content-center justify-content-center ppo-b2-light ppo-box-shadow ppo-bg-secondary text-light fs-5" id="ppoFilterSubmitButton">Find</button>
				</div>

			</div>

		</div>
	</div>

	<!-- Search Query -->
	<div class="row mb-4 justify-content-center">
		<div class="d-inline-flex ppo-box-shadow ppo-br-16 py-2 px-5 ppo-section-header ppo-bg-secondary w-auto">
			<h3 id="ppoSearchQuery" class="text-light fs-5 fw-bold mb-0">___</h3>
		</div>
	</div>

	<!-- Search Results -->
	<div class="row mb-4 py-2" id="ppoDaycareSearchResultContainer">
		<?php ppo_get_daycare_grid_list(); ?>
    </div>

    <!-- View More Button -->
    <div class="row mb-5 justify-content-center">
        <button class="btn py-1 w-50 ppo-br-16 ppo-box-shadow ppo-bg-primary text-light fw-bold fs-5 ml-4 mb-2 ppo-load-more">
            Vis flere
        </button>
    </div>
	
	
	<!-- /SEO Content -->
	<?php ppo_seo_content_embeded(); ?>

</article><!-- #post-<?php the_ID(); ?> -->

<!-- Popup Modal -->
<?php ppo_popup_modal(); ?>
<?php ppo_profile_page_popup_modal(); ?>

<script>
	"use strict";

	// 
	jQuery(function($){ // use jQuery code inside this to avoid "$ is not defined" error
		let currentPage=1;
				
		let queryInputInterval,
			prevValue;
		function ppoStopTriggeringSearchAjaxCall() {
		  clearInterval(queryInputInterval);
		}
		
		// Search Action
		$('#ppoZipSearch').on('input', function(e) {
						
			const currentValue = e.target.value;
			ppoStopTriggeringSearchAjaxCall()
			
			function myTimer() {
				$.ajax({ // you can also use $.post here
					url : ppo_data.ajax_url, // AJAX handler
					data : {
						query: currentValue ?? '',
						action: 'ppo_zipcode_search_action'
					},
					type : 'POST',
					dataType: 'html',
					beforeSend : function ( xhr ) {
						console.log("SENDING REQUEST...")
						const query = currentValue ? currentValue : '___';
						$("#ppoSearchQuery").html(query)
						$("#ppoDaycareSearchResultContainer").html(`
							<div class="d-flex w-100 justify-content-center align-items-center" style="height:400px;">
								<div class="loadingio-spinner-eclipse-vlgr8szkp9">
									<div class="ldio-ebuuj6igisj">
										<div></div>
									</div>
								</div>
							</div>
						`)
						$( '.ppo-load-more' ).fadeOut()
					},
					success : function( data, status, xhr ){
						console.log(status)
						if( data ) {
							
							$("#ppoDaycareSearchResultContainer").html(data)
							if($('#ppoDaycareSearchResultContainer [data-daycare-id]').length < 4 ) $( '.ppo-load-more' ).fadeOut()
							else $( '.ppo-load-more' ).fadeIn()
							
						} else {
							$("#ppoDaycareSearchResultContainer").html(`
								<div class="row mb-4 ppo-br-16 ppo-box-shadow">
									<div class="mb-3 p-4">
										<div class="text-center mb-4">
											<img src="<?php echo ppo_get_dir("/assets/images/crying.png"); ?>" style="width:10rem;" />
										</div>
										<style>
											.entry-content p {
												margin-bottom: 0.5rem;
											}
										</style>
										<div class="ppo-entry-content">
											<p class="text-center fs-5 fw-bold text-dark mb-2">Desværre!</p>
											<p class="text-center fs-5 fw-bold text-dark mb-0">Ingen profiler oprettet under dette postnummer Søg eventuelt et andet postnummer, nær dig.</p>
										</div>
									</div>
								</div>
							`);
							$( '.ppo-load-more' ).fadeOut()
						}
					},
					error: function(error) {
						console.log("ERROR")
						console.log(error)
					},
					complete: function(xhr) {
						console.log("COMPLETED")
					}
				});
				ppoStopTriggeringSearchAjaxCall()
			  	
			}
			
			if(prevValue != currentValue) queryInputInterval = setInterval(myTimer, 750);
			prevValue = currentValue;
		
		});
		
		//Filter Search
		$("#ppoFilterSubmitButton").on("click", (e) => {
			
			console.log(jQuery("button[data-targeted-plan].active").data("targeted-plan"))
			
			$.ajax({ // you can also use $.post here
				url : ppo_data.ajax_url, // AJAX handler
				data : {
					query: $('#ppoZipSearch').val(),
					plan: jQuery("button[data-targeted-plan].active").data("targeted-plan") ?? '',
					action: 'ppo_zipcode_filter_action'
				},
				type : 'POST',
				dataType: 'html',
				beforeSend : function ( xhr ) {
					console.log("SENDING REQUEST...")
// 					const query = currentValue ? currentValue : '___';
// 					$("#ppoSearchQuery").html(query)
					$("#ppoDaycareSearchResultContainer").html(`
						<div class="d-flex w-100 justify-content-center align-items-center" style="height:400px;">
							<div class="loadingio-spinner-eclipse-vlgr8szkp9">
								<div class="ldio-ebuuj6igisj">
									<div></div>
								</div>
							</div>
						</div>
					`)
					$( '.ppo-load-more' ).fadeOut()
				},
				success : function( data, status, xhr ){
					console.log(status)
					if( data ) {

						$("#ppoDaycareSearchResultContainer").html(data)
						if($('#ppoDaycareSearchResultContainer [data-daycare-id]').length < 4 ) $( '.ppo-load-more' ).fadeOut()
						else $( '.ppo-load-more' ).fadeIn()

					} else {
						$("#ppoDaycareSearchResultContainer").html(`
							<div class="row mb-4 ppo-br-16 ppo-box-shadow">
								<div class="mb-3 p-4">
									<div class="text-center mb-4">
										<img src="<?php echo ppo_get_dir("/assets/images/crying.png"); ?>" style="width:10rem;" />
									</div>
									<style>
										.entry-content p {
											margin-bottom: 0.5rem;
										}
									</style>
									<div class="ppo-entry-content">
										<p class="text-center fs-5 fw-bold text-dark mb-2">Desværre!</p>
										<p class="text-center fs-5 fw-bold text-dark mb-0">Ingen profiler oprettet under dette postnummer Søg eventuelt et andet postnummer, nær dig.</p>
									</div>
								</div>
							</div>
						`);
						$( '.ppo-load-more' ).fadeOut()
					}
				},
				error: function(error) {
					console.log("ERROR")
					console.log(error)
				},
				complete: function(xhr) {
					console.log("COMPLETED")
				}
			});
		});
		
		
		// Load More Ajax
		$('.ppo-load-more').click(function(){

			const button = $(this),
				data = {
					action: 'ppo_zipcode_search_result_load_more_action',
					// 	'query': ppo_data.posts, // that's how we get params from wp_localize_script() function
					paged : currentPage,
					query: $('#ppoZipSearch').val() ?? ''
				};

			$.ajax({ // you can also use $.post here
				url : ppo_data.ajax_url, // AJAX handler
				data : data,
				type : 'POST',
				dataType: 'html',
				beforeSend : function ( xhr ) {
					button.text('Indlæser...'); // change the button text, you can also add a preloader image
					button.prop("disabled", true)
				},
				success : function( data, status, xhr ){
					console.log(status)
					if( data ) {

						$("#ppoDaycareSearchResultContainer").append(data)

						currentPage++;
						
						console.log(currentPage)

						if ( currentPage == 3 /*ppo_data.max_page*/ ) 
							button.remove(); // if last page, remove the button

						// you can also fire the "post-load" event here if you use a plugin that requires it
						// $( document.body ).trigger( 'post-load' );

					} else {
						button.remove(); // if no data, remove the button as well
					}
				},
				error: function(error) {
					console.log("ERROR")
					console.log(error)
				},
				complete: function(xhr) {
					console.log("COMPLETED")
					button.text('Flere spørgsmål');
					button.prop("disabled", false)
				}
			});
		});
	});
						
					
	
	jQuery(document).ready(function($) {
		jQuery('button[data-targeted-year]').on("click", function(ele) {
			ele.preventDefault();
			jQuery("button[data-targeted-year].active").removeClass("active");
			ele.target.classList.toggle("active");
		});
		jQuery('button[data-targeted-month]').on("click", function(ele) {
			ele.preventDefault();
			jQuery("button[data-targeted-month].active").removeClass("active");
			ele.target.classList.toggle("active");
		});
		jQuery('button[data-targeted-plan]').on("click", function(ele) {
			ele.preventDefault();
			jQuery("button[data-targeted-plan].active").removeClass("active");
			ele.target.classList.toggle("active");
		});
	});

	function ppoToggleFilterContent() {
		if (jQuery("#ppoFilterContent")) jQuery("#ppoFilterContent").toggle('slow')
	};
</script>